dist: trusty
sudo: false

language: go

go_import_path: github.com/src-d/datasets
go:
  - 1.9.x
  - 1.10.x

before_install:
  - go get -v github.com/golang/lint/golint

script:
  - if [[ "$(go version)" != *go1.8* ]]; then go vet ./...; fi
  - lintwarns=$(golint ./... | grep src-d/datasets || true)
  - if [ ! -z $lintwarns ]; then echo $lintwarns; false; fi
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: deploy
      os: osx
      go: 1.9
      after_success:
        - gzip -S .darwin_amd64.gz $GOPATH/bin/multitool
        - tar -czf $GOPATH/bin/borges-indexer.darwin_amd64.tar.gz -C $GOPATH/bin borges-indexer set-forks
        - gzip -S .darwin_amd64.gz $GOPATH/bin/pga
      install:
        - go get -v github.com/src-d/datasets/PublicGitArchive/multitool/...
        - go get -v github.com/src-d/datasets/PublicGitArchive/borges-indexer/...
        - go get -v github.com/src-d/datasets/PublicGitArchive/pga/...
      script: skip
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file:
          - "$GOPATH/bin/multitool.darwin_amd64.gz"
          - "$GOPATH/bin/borges-indexer.darwin_amd64.tar.gz"
          - "$GOPATH/bin/pga.darwin_amd64.gz"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      os: linux
      go: 1.9
      install:
        - go get -v github.com/src-d/datasets/PublicGitArchive/multitool/...
        - go get -v github.com/src-d/datasets/PublicGitArchive/borges-indexer/...
        - go get -v github.com/src-d/datasets/PublicGitArchive/pga/...
      script: skip
      after_success:
        - gzip -S .linux_amd64.gz $GOPATH/bin/multitool
        - tar -czf $GOPATH/bin/borges-indexer.linux_amd64.tar.gz -C $GOPATH/bin borges-indexer set-forks
        - gzip -S .linux_amd64.gz $GOPATH/bin/pga
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file:
          - "$GOPATH/bin/multitool.linux_amd64.gz"
          - "$GOPATH/bin/borges-indexer.linux_amd64.tar.gz"
          - "$GOPATH/bin/pga.linux_amd64.gz"
        skip_cleanup: true
        on:
          tags: true

notifications:
  email: false
